### ISSUE TITLE
Please give us more :) 

### ISSUE THREAD

**Issue by brunakov** [zedr/clean-code-python#15]
Greatly appreciate your documents here ! 
Are there any plans for completing the rest of the article , i.e. https://github.com/zedr/clean-code-python#objects-and-data-structures and https://github.com/zedr/clean-code-python#classes ?
Thank you in advance!

**Comment by ziofil** [comment]
Yep, the core of the subject is missing.

**Comment by zedr** [comment]
Sorry about that. I have some other content that I'll add this weekend. Thanks for pointing it out.

**Comment by shahrukhx01** [comment]
+1

**Comment by zedr** [comment]
Done ;)
