### ISSUE TITLE
Using `str` instead of `Text`

### ISSUE THREAD

**Issue by yourhonor1996** [zedr/clean-code-python#22]
Hi! Thanks so much for your efforts, well done, excited for more!

One thought...
you have used the `Text` typing instead of `str` in your functions. Take a look at [this link](https://stackoverflow.com/questions/65624566/text-vs-str-when-using-python-type-hints).
I think it's better to use `str` instead of `Text` unless we want backward compatibility for python2 code.

**Comment by zedr** [comment]
Thanks for commenting on this. I think you're right in jettisoning PY2 compatibility. Would you like to submit a pull request with the changes?

**Comment by yourhonor1996** [comment]
sure, will make some time to it.
