### ISSUE TITLE
Translated to Persian language

### ISSUE THREAD

**Issue by khodealib** [zedr/clean-code-python#23]
After studying this repository, I decided to translate it into Persian, is there any problem?

**Comment by zedr** [comment]
Hi @khodealib . It would be a honor. Thanks for considering it.

**Comment by SepehrRasouli** [comment]
Hi @zedr, Can I be assigned to the translation ?

**Comment by zedr** [comment]
@SepehrRasouli sure, thank you. Keep in mind that I'll be adding the missing content in the following days, so you might want to wait until I have finished.

**Comment by SepehrRasouli** [comment]
Sure @zedr, I'll wait until you finish adding the missing content. Thanks :)

**Comment by zedr** [comment]
I'm done. :)

**Comment by SepehrRasouli** [comment]
Hi @zedr, I finished translating this repo to Persian, Can you please add my [translated](https://github.com/SepehrRasouli/clean-code-python) repo link to the repo ?

**Comment by zedr** [comment]
This is awesome. Thanks!
